
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lang.parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int CHAR_TYPE = 35;
  public static final int BOOL_TYPE = 36;
  public static final int LBRACKET = 6;
  public static final int MULT = 16;
  public static final int CHAR_LITERAL = 27;
  public static final int LPAREN = 4;
  public static final int RPAREN = 5;
  public static final int DATA = 33;
  public static final int NOT = 24;
  public static final int SEMICOLON = 9;
  public static final int AND = 23;
  public static final int LT = 21;
  public static final int COMMA = 8;
  public static final int DIV = 17;
  public static final int PLUS = 14;
  public static final int IF = 38;
  public static final int DOT = 12;
  public static final int ID = 31;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int RBRACKET = 7;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int ATBR = 13;
  public static final int NULL = 30;
  public static final int MOD = 18;
  public static final int NEQ = 20;
  public static final int INT_TYPE = 34;
  public static final int EQ = 19;
  public static final int TYID = 32;
  public static final int ITERATE = 40;
  public static final int COLON = 10;
  public static final int ELSE = 39;
  public static final int LBRACE = 2;
  public static final int READ = 41;
  public static final int DOUBLE_COLON = 11;
  public static final int RBRACE = 3;
  public static final int FLOAT_LITERAL = 26;
  public static final int FALSE = 29;
  public static final int FLOAT_TYPE = 37;
  public static final int GT = 22;
  public static final int SUB = 15;
  public static final int PRINT = 43;
  public static final int INT_LITERAL = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "DOUBLE_COLON",
  "DOT",
  "ATBR",
  "PLUS",
  "SUB",
  "MULT",
  "DIV",
  "MOD",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "AND",
  "NOT",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "CHAR_LITERAL",
  "TRUE",
  "FALSE",
  "NULL",
  "ID",
  "TYID",
  "DATA",
  "INT_TYPE",
  "CHAR_TYPE",
  "BOOL_TYPE",
  "FLOAT_TYPE",
  "IF",
  "ELSE",
  "ITERATE",
  "READ",
  "RETURN",
  "PRINT"
  };
}

