
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class LangParserSym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 5;
  public static final int TRUE = 3;
  public static final int INT_LITERAL = 2;
  public static final int FALSE = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT_LITERAL",
  "TRUE",
  "FALSE",
  "PLUS"
  };
}

